export const GROUP_TODOS_STARTED   = 'GROUP_TODOS_STARTED';
export const GROUP_TODOS_SUCCESS   = 'GROUP_TODOS_SUCCESS';
export const ADD_NEW_GROUP_STARTED = 'ADD_NEW_GROUP_STARTED';
export const ADD_NEW_GROUP_SUCCESS = 'ADD_NEW_GROUP_SUCCESS';
