export const GROUP_STARTED         = 'GROUP_STARTED';
export const GROUP_SUCCESS         = 'GROUP_SUCCESS';
export const ADD_NEW_GROUP_STARTED = 'ADD_NEW_GROUP_STARTED';
export const ADD_NEW_GROUP_SUCCESS = 'ADD_NEW_GROUP_SUCCESS';
